spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/productDb
    username: postgres
    password: 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

cache:
  config:
  entryTtl: 60
  countryNames:
    entryTtl: 30
#logging:
#  level:
#    root: info

#discount:
#  grpc:
#    host: localhost
#    port: 9090
#
#server:
#  port: 8080
